### PR TITLE
Create Decrypt data using expressions.policy.xml

### PR DESCRIPTION
**Pull request by falrnacn**
This policy snippet shows how to decrypt an AES 192 bit encrypted text and return it to caller. The encrypted text is sent as a JSON element.

### CODE REVIEW

**Comment by falrnacn** [comment]
@microsoft-github-policy-service agree

**Review by adrianhall — APPROVED** [review]

**Comment by adrianhall** [comment]
Please rename file to "Decrypt AES Data using policy expressions.xml" - I'd also suggest wrapping this in a more full featured example - for example, decrypting an encrypted cookie or similar.

**Comment by adrianhall** [comment]
Closes #37

**Comment by falrnacn** [comment]
> 

Hi @adrianhall 
I have renamed the file as suggested.

**Comment by falrnacn** [comment]
@adrianhall I see that post your approval, Merging is still blocked. 
"Merging is blocked
Merging can be performed automatically with 1 approving review."
Can you please let me know when it will be merged and do i need to do anything else?

**Comment by adrianhall** [comment]
I am no longer a member of the right team.  Cc: @mikebudzynski for completion.

**Review by mikebudzynski — APPROVED** [review]

**Pull request merged**
