### PR TITLE
ADD: new policy example for loopback call, also with update on readme.md

### PR DESCRIPTION
**Pull request by gfchaves**

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Adding @vladvino

**Review by vladvino — COMMENTED** [review]
@gfchaves can you describe the use case that prompted you to create this policy for?

**Comment by vladvino** [comment]
@maksimkim please review and comment.

**Comment by gfchaves** [comment]
@vladvino we're preparing a full blog post to describe the use case. Although and to resume it's all about when you have your APIm instance deployed with a virtual private network and you need to perform HTTP requests at services that are deployed on the same instance. If you don't add the Host header, you'll get a 500 internal server error. 

We discovered this "fix" /tip with help of Azure support team that encouraged us to document this case and to contribute at the repos and documentation.

**Review by vladvino — COMMENTED** [review]
@gfchaves please change "apim" "Apim" "APim" etc. to "API Management service"

**Comment by gfchaves** [comment]
@vladvino changed as suggested. PR updated.

**Review by vladvino — COMMENTED** [review]
Thank you, @gfchaves. You missed one occurrence in the readme file.

**Comment by gfchaves** [comment]
@vladvino changed as suggested, also changed the file name to match with name convention.  PR updated, thankyou once again.

**Review by vladvino — APPROVED** [review]
Thank you!

**Pull request merged**
